artifact_location: file:///C:/Users/amil/OneDrive/Documents/mlops/mlflow_with_aws/ec2-65-0-105-205.ap-south-1.compute.amazonaws.com/0
creation_time: 1753037278996
experiment_id: '0'
last_update_time: 1753037278996
lifecycle_stage: active
name: Default
